# Generated by Django 6.0.6 on 2026-06-23 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, 'wrong number')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
